qxb3/fum

README.md

Feel free to change anything, just thought It would be nice to be able to see the available keystrokes right away :)
love the project <3

chore: Add keystrokes to README.md

---

Cargo.lock
Cargo.toml
src/meta.rs
src/ui.rs
src/utils/player.rs

more metadata

---

README.md
flake.lock
flake.nix
nix/default.nix
nix/hm-module.nix

I write a little flake to install in NixOS or nix based systems.
Here is a instructions to add to wiki or idk. Tell me if you need something!
To install `fum` using Nix Flakes and configure it with `configuration.nix`, follow these steps:
1. Add `fum` as an input in your `flake.nix`:
```nix
{
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
flake-utils.url = "github:numtide/flake-utils";
fum.url = "github:qxb3/fum";
};
outputs = { self, nixpkgs, flake-utils, fum }:
flake-utils.lib.eachDefaultSystem (system: let
pkgs = import nixpkgs { inherit system; };
in {
nixosConfigurations = {
hostname = pkgs.lib.nixosSystem {
system = system;
modules = [
./configuration.nix
fum.nixosModules.fum
{
services.fum = {
enable = true;
players = ["spotify"];
use_active_player = true;
align = …
```

feat(flake.nix): create a flake and nixModule

---

src/config/defaults.rs
src/widget.rs

fix action

---

src/action.rs

forward() & backward() actions

---

Cargo.lock
Cargo.toml
src/config/config.rs
src/config/defaults.rs
src/ui.rs
src/utils/etc.rs
src/widget.rs

added bg and bg on widgets

---

src/action.rs
src/meta.rs

forward(), backward() action improvements

---

src/config/defaults.rs
src/ui.rs
src/widget.rs

seperate color for progress and empty

---

src/config/defaults.rs
src/widget/cover_art.rs
src/widget/widget.rs

Adds `resize` prop on the `cover-art`:
```json
{
"type": "cover-art",
"width": 20,
"resize": "scale" // fit, crop
}
```

resize props on cover-art

---

Cargo.lock
Cargo.toml
src/action.rs
src/fum.rs
src/main.rs
src/regexes.rs
src/state.rs
src/text.rs
src/ui.rs
src/utils/etc.rs
src/widget/button.rs
src/widget/container.rs
src/widget/cover_art.rs
src/widget/empty.rs
src/widget/label.rs
src/widget/progress.rs
src/widget/widget.rs

#11 
Plan:
```json
{
"type": "button",
"text": "var($foo, $length)",
"action": "toggle($foo, $length, $remaining-length)"
}
```
along with `toggle()` action we will have `set()` action
set:
```json
{
"type": "button",
"text": "var($foo, $length)",
"action": "set($foo, $title)"
}
```

introducing variable

---

src/config/config.rs
src/config/defaults.rs
src/state.rs
src/ui.rs
src/widget/cover_art.rs

Cover art ascii

---

Cargo.lock
Cargo.toml
src/widget/widget.rs

#46 
This handles special unicode width.

Handle unicode width

---

src/regexes.rs

support for hyphen on var

---

src/action.rs
src/meta.rs

optional mpris meta support

---

src/action.rs
src/regexes.rs

#56 
value is 0 - 100
`volume(-10)` decreases volume
`volume(+10)` increases volume
`volume(50)`  sets the volume to 50

volume() action

---

README.md

https://github.com/qxb3/fum/commit/bc4d1a59586e63ad6b56bae09545f3f7a62a8189

readme: bring back manual install instructions

---

src/regexes.rs
src/text.rs

`lower(some text lowered cased)`
`lower($title)`
`upper(some text upper cased)`
`upper($title)`

adds lower() & upper() text action

---

src/text.rs

just to keep the consistency
`$status_icon` -> `$status-icon`

change $status_icon var to kebab case

---

src/meta.rs
src/text.rs

@danielwerg specifically for ur lowfi clone rice, if u want to replace the controls to be also text instead of nerdfont icons

adds $status-text var

---

src/meta.rs

update volume ui

---

src/config/config.rs
src/config/defaults.rs
src/ui.rs
src/widget/container.rs
src/widget/cover_art.rs
src/widget/widget.rs

adds border property on widgets

---

src/config/defaults.rs
src/widget/button.rs
src/widget/label.rs
src/widget/widget.rs

not sures if it works since i dont have a font that supports bold. will merge it anyway.
#71 #68

adds bold property on label & button

---

src/action.rs

fixes https://github.com/qxb3/fum/pull/72#issuecomment-2641620955

fix pos capability

---

src/fum.rs

fixes https://github.com/qxb3/fum/pull/72#issuecomment-2641620955

fix continuesly skips when drag

---

src/meta.rs

fix ui update on backward(-1)

---

src/config/defaults.rs
src/utils/etc.rs
src/widget/button.rs
src/widget/label.rs
src/widget/widget.rs

vertical text on label / button #71

adds direction on label & button

---

src/cli.rs
src/config/config.rs
src/config/defaults.rs

config:
```jsonc
{
...
"fps": 60, // 60 fps (default is 10fps)
...
}
```
cli:
```bash
fum --fps 60 # default is 10fps
```

adds fps config/cli

---

src/config/config.rs
src/config/defaults.rs
src/ui.rs
src/widget/container.rs
src/widget/widget.rs

added padding on:
* main fum container
* container
#71 #68

added padding

---

src/text.rs
src/utils/widget.rs

Added text variable variant:
* `position-ext`
* `remaining-length-ext`
* `length-ext`
> Not necessary minutes but rather first number section in length:
> 
> 3:24
> ^
>
> 2:02:09
> ^
>
> 1:56 -> 01:56
> -1:30 -> -01:30
> 0:09 -> 00:09

added *duration-ext

---

doc-site/src/app.css
doc-site/static/icons/check.svg
doc-site/static/icons/copy.svg
doc-site/vite.config.ts

fully keyboard-navigable (copy and scroll when needed)
tested on firefox and chromium

feat(docs): codeblock copy button
